# Generated by Django 3.2.15 on 2024-08-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('raw_concentration', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.IntegerField()),
                ('data_type', models.CharField(choices=[('unsigned short', 'Unsigned Short'), ('float', 'Float')], max_length=20)),
                ('read_write', models.CharField(choices=[('R', 'Read Only'), ('R/W', 'Read/Write')], max_length=3)),
                ('command', models.CharField(max_length=10)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('last_read_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modbusrtu.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
    ]
