from django.db import migrations

def create_initial_data(apps, schema_editor):
    Category = apps.get_model('modbusrtu', 'Category')
    DataItem = apps.get_model('modbusrtu', 'DataItem')

    data_categories = {
        "版本信息": [
            {"name": "软件版本", "address": 0x0000, "data_type": "unsigned short", "read_write": "R", "command": "03"},
            {"name": "硬件版本", "address": 0x0001, "data_type": "unsigned short", "read_write": "R", "command": "03"},
        ],
        "序列号": [
            {"name": "板序列号低", "address": 0x0002, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03"},
            {"name": "板序列号中", "address": 0x0003, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03"},
            {"name": "板序列号高", "address": 0x0004, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03"},
        ],
        "系统运行时间": [
            {"name": "系统运行时间（年）", "address": 0x0005, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "系统运行时间（月）", "address": 0x0006, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "系统运行时间（日）", "address": 0x0007, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "系统运行时间（时）", "address": 0x0008, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "系统运行时间（分）", "address": 0x0009, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "系统运行时间（秒）", "address": 0x000A, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
        "运行模式": [
            {"name": "运行模式", "address": 0x000B, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
        "测试时间": [
            {"name": "开始测试时间（时）", "address": 0x000C, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "开始测试时间（分）", "address": 0x000D, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "开始测试时间（秒）", "address": 0x000E, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
        "测试间隔时间": [
            {"name": "测试间隔时间（时）", "address": 0x000F, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "测试间隔时间（分）", "address": 0x0010, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "测试间隔时间（秒）", "address": 0x0011, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
        "系统控制": [
            {"name": "系统整体复位命令", "address": 0x0012, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
        "通讯状态": [
            {"name": "H2板通讯状态", "address": 0x0013, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "H2O板通讯状态", "address": 0x0014, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "CO2板通讯状态", "address": 0x0015, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "CO板通讯状态", "address": 0x0016, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "CH4板通讯状态", "address": 0x0017, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "C2H2板通讯状态", "address": 0x0018, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "C2H4板通讯状态", "address": 0x0019, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "C2H6板通讯状态", "address": 0x001A, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "脱气板通讯状态", "address": 0x001B, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
        ],
        "系统状态": [
            {"name": "系统模式运行进程", "address": 0x001C, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "主控板发送停止状态", "address": 0x001D, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
        ],
        "运行状态": [
            {"name": "H2板运行状态", "address": 0x001E, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "H2O板运行状态", "address": 0x001F, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "CO2板运行状态", "address": 0x0020, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "CO板运行状态", "address": 0x0021, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "CH4板运行状态", "address": 0x0022, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "C2H2板运行状态", "address": 0x0023, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "C2H4板运行状态", "address": 0x0024, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "C2H6板运行状态", "address": 0x0025, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
            {"name": "脱气板运行状态", "address": 0x0026, "data_type": "unsigned short", "read_write": "R",
             "command": "03"},
        ],
        "配置": [
            {"name": "油中浓度值平均次数及气体种类", "address": 0x0027, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "现场运行模式", "address": 0x0028, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
        "故障信息": [
            {"name": "脱气故障码", "address": 0x0029, "data_type": "unsigned short", "read_write": "R", "command": "03"},
        ],
        "气体浓度": [
            {"name": "H2浓度", "address": 0x002A, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "H2O浓度", "address": 0x002C, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "CO2浓度", "address": 0x002E, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "CO浓度", "address": 0x0030, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "CH4浓度", "address": 0x0032, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "C2H2浓度", "address": 0x0034, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "C2H4浓度", "address": 0x0036, "data_type": "float", "read_write": "R", "command": "03"},
            {"name": "C2H6浓度", "address": 0x0038, "data_type": "float", "read_write": "R", "command": "03"},
        ],
        "气体浓度(传感器原始值)": [
            {"name": "H2浓度(单位:ppm 传感器原始值)", "address": 0x003A, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "H2O浓度(单位:ppm 传感器原始值)", "address": 0x003C, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "CO2浓度(单位:ppm 传感器原始值)", "address": 0x003E, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "CO浓度(单位:ppm 传感器原始值)", "address": 0x0040, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "CH4浓度(单位:ppm 传感器原始值)", "address": 0x0042, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "C2H2浓度(单位:ppm 传感器原始值)", "address": 0x0044, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "C2H4浓度(单位:ppm 传感器原始值)", "address": 0x0046, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "C2H6浓度(单位:ppm 传感器原始值)", "address": 0x0048, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "测量时气体温度（C2H2温度,℃）", "address": 0x004A, "data_type": "float", "read_write": "R",
             "command": "03"},
            {"name": "测量时气体压力（C2H2温度，Pa）", "address": 0x004C, "data_type": "float", "read_write": "R",
             "command": "03"},
        ],
        "H2参数": [
            {"name": "H2浓度:温度", "address": 0x004E, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2浓度:压力", "address": 0x0050, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2浓度: 线性度系数（a1x+b1----a1）", "address": 0x0052, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2浓度: 零点值（a1x+b1----b1）", "address": 0x0054, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2传感器选择", "address": 0x0056, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2浓度：线性度系数（ax+b----a）", "address": 0x0058, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2浓度：零点值（ax+b----b）", "address": 0x005A, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "H2O参数": [
            {"name": "H2O浓度:温度", "address": 0x005C, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2O浓度:压力", "address": 0x005E, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2O浓度: 线性度系数（a1x+b1----a1）", "address": 0x0060, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2O浓度: 零点值（a1x+b1----b1）", "address": 0x0062, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2O浓度:高浓度标定系数", "address": 0x0064, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2O浓度:线性度系数（ax+b----a）", "address": 0x0066, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "H2O浓度:零点值（ax+b----b）", "address": 0x0068, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "CO2参数": [
            {"name": "CO2浓度:温度", "address": 0x006A, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "CO2浓度:压力", "address": 0x006C, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "CO2浓度: 线性度系数（a1x+b1----a1）", "address": 0x006E, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO2浓度: 零点值（a1x+b1----b1）", "address": 0x0070, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO2浓度:高浓度标定系数", "address": 0x0072, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO2浓度:线性度系数（ax+b----a）", "address": 0x0074, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO2浓度:零点值（ax+b----b）", "address": 0x0076, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "CO参数": [
            {"name": "CO浓度:温度", "address": 0x0078, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "CO浓度:压力", "address": 0x007A, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "CO浓度: 线性度系数（a1x+b1----a1）", "address": 0x007C, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO浓度: 零点值（a1x+b1----b1）", "address": 0x007E, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO浓度:高浓度标定系数", "address": 0x0080, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO浓度:线性度系数（ax+b----a）", "address": 0x0082, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CO浓度:零点值（ax+b----b）", "address": 0x0084, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "CH4参数": [
            {"name": "CH4浓度:温度", "address": 0x0086, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "CH4浓度:压力", "address": 0x0088, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "CH4浓度: 线性度系数（a1x+b1----a1）", "address": 0x008A, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CH4浓度: 零点值（a1x+b1----b1）", "address": 0x008C, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CH4浓度:高浓度标定系数", "address": 0x008E, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CH4浓度:线性度系数（ax+b----a）", "address": 0x0090, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "CH4浓度:零点值（ax+b----b）", "address": 0x0092, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "C2H2参数": [
            {"name": "C2H2浓度:温度", "address": 0x0094, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H2浓度:压力", "address": 0x0096, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H2浓度: 线性度系数（a1x+b1----a1）", "address": 0x0098, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H2浓度: 零点值（a1x+b1----b1）", "address": 0x009A, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H2浓度:高浓度标定系数", "address": 0x009C, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H2浓度:线性度系数（ax+b----a）", "address": 0x009E, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H2浓度:零点值（ax+b----b）", "address": 0x00A0, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "C2H4参数": [
            {"name": "C2H4浓度:温度", "address": 0x00A2, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H4浓度:压力", "address": 0x00A4, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H4浓度: 线性度系数（a1x+b1----a1）", "address": 0x00A6, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H4浓度: 零点值（a1x+b1----b1）", "address": 0x00A8, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H4浓度:高浓度标定系数", "address": 0x00AA, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H4浓度:线性度系数（ax+b----a）", "address": 0x00AC, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H4浓度:零点值（ax+b----b）", "address": 0x00AE, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "C2H6参数": [
            {"name": "C2H6浓度:温度", "address": 0x00B0, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H6浓度:压力", "address": 0x00B2, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H6浓度: 线性度系数（a1x+b1----a1）", "address": 0x00B4, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H6浓度: 零点值（a1x+b1----b1）", "address": 0x00B6, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H6浓度:高浓度标定系数", "address": 0x00B8, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H6浓度:线性度系数（ax+b----a）", "address": 0x00BA, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "C2H6浓度:零点值（ax+b----b）", "address": 0x00BC, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "O2和N2浓度": [
            {"name": "O2（单位:ppm 换算后的结果）", "address": 0x00BE, "data_type": "float", "read_write": "R",
             "command": "03/10"},
            {"name": "N2（单位:ppm 换算后的结果）", "address": 0x00C0, "data_type": "float", "read_write": "R",
             "command": "03/10"},
            {"name": "O2 (单位:ppm 传感器原始值)", "address": 0x00C2, "data_type": "float", "read_write": "R",
             "command": "03/10"},
            {"name": "N2 (单位:ppm 传感器原始值)", "address": 0x00C4, "data_type": "float", "read_write": "R",
             "command": "03/10"},
        ],
        "O2参数": [
            {"name": "O2浓度:标气线性校准系数", "address": 0x00C6, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "O2浓度:油转气标定系数", "address": 0x00C8, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "O2浓度:高浓度标定系数", "address": 0x00CA, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "O2:线性度系数（ax+b----a）", "address": 0x00CC, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "O2:零点值（ax+b----b）", "address": 0x00CE, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "N2参数": [
            {"name": "N2浓度:油转气标定系数", "address": 0x00D2, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "N2浓度:高浓度标定系数", "address": 0x00D4, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "N2:线性度系数（ax+b----a）", "address": 0x00D6, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "N2:零点值（ax+b----b）", "address": 0x00D8, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
            {"name": "N2浓度:标气线性校准系数", "address": 0x00DA, "data_type": "float", "read_write": "R/W",
             "command": "03/10"},
        ],
        "其他参数": [
            {"name": "总烃（20190830山东修改）", "address": 0x00D0, "data_type": "float", "read_write": "R/W",
             "command": "03"},
        ],
        "告警设置": [
            {"name": "告警灯控制开关", "address": 0x00DC, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "主控板ModBUS地址", "address": 0x00DD, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "H2告警门限", "address": 0x00DE, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H2告警门限", "address": 0x00E0, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "总烃告警门限", "address": 0x00E2, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2高告警门限", "address": 0x00E4, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "C2H2高告警门限", "address": 0x00E6, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "总烃高告警门限", "address": 0x00E8, "data_type": "float", "read_write": "R/W", "command": "03/10"},
        ],
        "系统控制": [
            {"name": "脱气告警1", "address": 0x00EA, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "自动加速监控功能开关", "address": 0x00EB, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "测试次数设置", "address": 0x00EC, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "脱气复位指示位", "address": 0x00ED, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03"},
            {"name": "脱气完成后的压力", "address": 0x00EE, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "油罐实时压力", "address": 0x00F0, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "油罐实时温度", "address": 0x00F2, "data_type": "float", "read_write": "R/W", "command": "03/10"},
            {"name": "H2/CO最小限值", "address": 0x00F6, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "CH4/C2H2最小限值", "address": 0x00F7, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "C2H4/C2H6最小限值", "address": 0x00F8, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "动态零点和清洗设置", "address": 0x00F9, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "抽真空压力门限设置", "address": 0x0102, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "下一次开始测试时间（时）", "address": 0x0104, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "下一次开始测试时间（分）", "address": 0x0105, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "油罐加热标志和时间", "address": 0x0106, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "手动选择油转气系数", "address": 0x0107, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "脱气调试命令", "address": 0x0108, "data_type": "unsigned short", "read_write": "W",
             "command": "06"},
        ],
        "湿度和序列号": [
            {"name": "CO湿度", "address": 0x010A, "data_type": "float", "read_write": "R/W", "command": "03/06"},
            {"name": "CH4湿度", "address": 0x010C, "data_type": "float", "read_write": "R/W", "command": "03/06"},
            {"name": "H2序列号", "address": 0x010E, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
            {"name": "CO序列号", "address": 0x0111, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
            {"name": "CO2序列号", "address": 0x0114, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
            {"name": "CH4序列号", "address": 0x0117, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
            {"name": "C2H2序列号", "address": 0x011A, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
            {"name": "C2H4序列号", "address": 0x011D, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
            {"name": "C2H6序列号", "address": 0x0120, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/10", "length": 3},
        ],
        "系统状态": [
            {"name": "脱气流程完成指示位", "address": 0x0123, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "脱气流程工作状态码", "address": 0x0124, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "CH4传感器故障码", "address": 0x0125, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "C2H2传感器故障码", "address": 0x0126, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "C2H4传感器故障码", "address": 0x0127, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "C2H6传感器故障码", "address": 0x0128, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "CO传感器故障码", "address": 0x0129, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
            {"name": "脱气进程步数", "address": 0x012A, "data_type": "unsigned short", "read_write": "R/W",
             "command": "03/06"},
        ],
    }

    for category_name, items in data_categories.items():
        category = Category.objects.create(name=category_name)
        for item in items:
            DataItem.objects.create(
                category=category,
                name=item['name'],
                address=item['address'],
                data_type=item['data_type'],
                read_write=item['read_write'],
                command=item['command']
            )

class Migration(migrations.Migration):

    dependencies = [
        ('modbusrtu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
